swagger: "2.0"
info:
  title: API do desafio Inter
  description: API Rest para gerenciar o crud de uma aplicação e chave criptografica.
  version: 1.0.1
  termsOfService: https://mockapi.io
  contact:
    name: Suporte da API
    email: cleiton.inside@gmail.com
    url: https://mockapi.io
  license:
    name: "Lincença: GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.html
externalDocs:
  description: Documentação burocrática
  url: https://mockapi.io
servers:
- url: https://618d9315fe09aa00174407fd.mockapi.io/
  description: API de Teste das requisições

schemes:
 - https
 - http
    
tags: 
  - name: "Consulta"
    description: "Acesso a operações de consulta de USUARIOS"
  - name: "Manutenção"
    description: "Acesso a operações de manutençao de USUARIOS"

paths:
  
  /usuarios:
    
    post:
      tags: 
        - "Manutenção"
      summary: "Cria novo usuario"
      operationId: "criarUsuario"
      description: "|
        endpoint *cria o* usuario."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "usuario"
        description: "Informações do Usuario."
        required: true
        schema:
          $ref: "#/definitions/Usuario"
      responses:
        201:
          description: "Novo usuario criado."
          schema:
            $ref: "#/definitions/Usuario"
          headers:
            Location:
              type: "string"
              description: "uri do novo usuario."
  
  /usuario/{id}:
    
    get:
      tags: 
        - "Consulta"
      summary: "Busca de usuario"
      operationId: "buscaUsuario"
      description: "|
        endpoint *busca o* usuario."
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Usuario"
          headers: {}
    
    put:
      tags: 
        - "Manutenção"
      summary: "Alteração de usuario"
      operationId: "alteraUsuario"
      description: "|
        endpoint *altera o* usuario."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Usuario alterado."
          schema:
            $ref: "#/definitions/Usuario"
    
    delete:
      tags: 
        - "Manutenção"
      summary: "Remove o usuario"
      description: "|
        endpoint *remove o* usuario."
      operationId: "removerUsuario"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Usuario removido."
          
definitions:
  Usuario:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "Id do usuario."
      nome:
        type: "string"
        description: "Nome do usuario"
      email:
        type: "string"
        description: "Email do usuario"
      digitounico:
        type: "string"
        description: "Digito Unico do usuario"
      chavepublica:
        type: "string"
        format: ""
        description: "Chave Publica do usuario"